### ISSUE TITLE
Interpreting Output

### ISSUE THREAD

**Issue by gblanchard4** [pgajer/MCclassifier#2]
I was wondering if you had information on how to interpret the output. I can understand that the first column is the sequence identifier,  and the second column is the taxa assignment. The third is _probably_ a score of some sort, but I don't know how to read it.

**Comment by pgajer** [comment]
Hi Gene,

Thank you rewriting the README file with markdown support.

the third column of the output is an estimate of the probability of
an erroneous taxonomic classification.

Best,
:)
pawel
